AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
