version: "3"
services:
  mariadb:
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    expose:
      - "3306"
    image: "mariadb"
  rails:
    build:
      args:
        GEMFILE: "Gemfile"
        GEMFILE_LOCK: "Gemfile.lock"
      context: "./"
      dockerfile: "./docker/rails/Dockerfile"
    environment:
      RAILS_DATABASE_HOST: "mariadb"
      RAILS_DATABASE_PASSWORD: "password"
      RAILS_DATABASE_PORT: "3306"
      RAILS_DATABASE_USERNAME: "root"
      RAILS_ROOT: "/var/www/app/"
      RAILS_SOLR_HOST: "solr"
      RAILS_SOLR_PATH: "/solr/mycore"
    image: "cojt-board-project-rails"
    ports:
      - "3000:3000"
    volumes:
      - "./:/var/www/app/"
  solr:
    entrypoint: "docker-entrypoint.sh solr-precreate mycore"
    expose:
      - "8983"
    image: "solr"
    ports:
      - "8983:8983"
