version: "3"
services:
  mariadb:
    environment:
      MYSQL_DATABASE: "cojtswbp_database"
      MYSQL_PASSWORD: "cojtswbp_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "cojtswbp_user"
    expose:
      - "3306"
    image: "mariadb"
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
  nginx:
    command: "/bin/sh -c \"envsubst '$$RAILS_ROOT' < /var/www/app/docker/nginx/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
    environment:
      RAILS_ROOT: "/var/www/app"
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/app"
  rails:
    build:
      args:
        GEMFILE: "Gemfile"
        GEMFILE_LOCK: "Gemfile.lock"
      context: "./"
      dockerfile: "./docker/rails/Dockerfile"
    command: "puma -w 4"
    environment:
      DOCKERIZE_HOSTS: "mariadb:3306 redis:6379 solr:8983"
      RAILS_DATABASE: "cojtswbp_database"
      RAILS_DATABASE_HOST: "mariadb"
      RAILS_DATABASE_PASSWORD: "cojtswbp_password"
      RAILS_DATABASE_USERNAME: "cojtswbp_user"
      RAILS_ENV: "production"
      RAILS_ROOT: "/var/www/app"
      RAILS_SOLR_HOST: "solr"
      RAILS_SOLR_PATH: "/solr/mycore"
      RAILS_TASKS: "assets:precompile db:create db:migrate db:seed sunspot:reindex"
    image: "cojt-board-project-rails"
    volumes:
      - "./:/var/www/app"
  redis:
    expose:
      - "6379"
    image: "redis"
  solr:
    entrypoint: "docker-entrypoint.sh solr-precreate mycore"
    expose:
      - "8983"
    image: "solr"
