version: "3"
services:
  mariadb:
    # in case of windows
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_c --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON"
    #command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: "cojtswbp_database"
      MYSQL_PASSWORD: "cojtswbp_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "cojtswbp_user"
    expose:
      - "3306"
    image: "mariadb"
    # in case of windows
    user: "1000:50"
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
    restart: always
  rails:
    build:
      args:
        GEMFILE: "Gemfile"
        GEMFILE_LOCK: "Gemfile.lock"
      context: "./"
      dockerfile: "./docker/rails/Dockerfile"
    command: "puma -w 4"
    environment:
      DOCKERIZE_HOSTS: "mariadb:3306 redis:6380 solr:8983"
      RAILS_DATABASE: "cojtswbp_database"
      RAILS_DATABASE_HOST: "mariadb"
      RAILS_DATABASE_PASSWORD: "cojtswbp_password"
      RAILS_DATABASE_USERNAME: "cojtswbp_user"
      RAILS_ENV: "production"
      RAILS_REDIS_HOST: "redis"
      RAILS_ROOT: "/var/www/app"
      RAILS_SOLR_HOST: "solr"
      RAILS_SOLR_PATH: "/solr/mycore"
      RAILS_TASKS: "assets:precompile db:create db:migrate db:seed sunspot:reindex"
    image: "cojt-board-project-rails"
    ports:
      - "4000:3000"
    volumes:
      - "./:/var/www/app"
    restart: always
  redis:
    expose:
      - "6380"
    image: "redis"
    restart: always
  solr:
    command: "solr-precreate mycore /var/lib/solr/config"
    expose:
      - "8983"
    image: "solr:6"
    volumes:
      - "./docker/solr/config:/var/lib/solr/config"
    restart: always
