version: "3"
services:
  mariadb:
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    expose:
      - "3306"
    image: "mariadb"
  rails:
    build:
      args:
        DEPLOY_USER_GID: "$GID"
        DEPLOY_USER_UID: "$UID"
        RAILS_GEMFILE: "Gemfile"
        RAILS_GEMFILE_LOCK: "Gemfile.lock"
      context: "./"
      dockerfile: "./docker-compose/dockerfile.rails"
    environment:
      RAILS_DATABASE_HOST: "mariadb"
      RAILS_DATABASE_PASSWORD: "password"
      RAILS_DATABASE_PORT: "3306"
      RAILS_DATABASE_USERNAME: "root"
    image: "cojt-board-project-rails"
    ports:
      - "3000:3000"
    volumes:
      - "./:/home/deploy/app"
