production:
  solr:
    hostname: <%= ENV['RAILS_SOLR_HOST'] %>
    port: 8983
    log_level: WARNING
    path: <%= ENV['RAILS_SOLR_PATH'] %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= ENV['RAILS_SOLR_HOST'] %>
    port: 8983
    log_level: INFO
    path: <%= ENV['RAILS_SOLR_PATH'] %>

test:
  solr:
    hostname: <%= ENV['RAILS_SOLR_HOST'] %>
    port: 8983
    log_level: WARNING
    path: <%= ENV['RAILS_SOLR_PATH'] %>
